export default  {
    GET_PRODUCTS: 'GET_PRODUCTS',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    HAS_ACCEPTED_TERMS: 'HAS_ACCEPTED_TERMS',
    TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
    TOGGLE_USER_DROPDOWN: 'TOGGLE_USER_DROPDOWN',
    GET_ALL_USERS: 'GET_ALL_USERS',
    ADD_ERROR: 'ADD_ERROR',
    REMOVE_ERROR: 'REMOVE_ERROR',
    GET_ALL_ORDERS: 'GET_ALL_ORDERS',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    CLEAR_ALL_ITEMS_FROM_CART: 'CLEAR_ALL_ITEMS_FROM_CART',
    CLEAR_CART: 'CLEAR_CART'




}